function lv(map) {
  return map;
}

function metric(id, title, description, levels) {
  return { id, title, description, levels: lv(levels) };
}

const LEVELS = [
  {
    id: 1,
    expected: 1.0,
    summary:
      'Works with close guidance on well-scoped GATE work. Learns product fundamentals and contributes safely. Impact is local and learning-driven.',
    promotionGates: [
      'Finish small, well-defined GATE tasks end-to-end with support',
      'Follow team workflows: branches, reviews, and status updates in Jira',
      'Raise blockers early with enough context for the next person',
      'Document what you learned and apply review feedback',
      'Show steady improvement across several sprints',
    ],
  },
  {
    id: 2,
    expected: 2.0,
    summary:
      'Delivers well-defined work with moderate guidance and growing independence. Impact is consistent contribution to sprint goals.',
    promotionGates: [
      'Deliver well-defined work from planning to production with little rework',
      'Work smoothly with QA, PO, and reviewers during a GATE sprint',
      'Give review comments that catch real issues, not only style',
      'Keep quality and delivery predictable across multiple sprints',
      'Clarify requirements when a ticket is incomplete',
    ],
  },
  {
    id: 3,
    expected: 3.0,
    summary:
      'Delivers independently across design, implementation, test, and release. Handles moderate ambiguity. Impact is reliable execution at team level.',
    promotionGates: [
      'Own features end-to-end with predictable quality and light oversight',
      'Turn partially defined problems into a clear plan and a working change',
      'Lead work that spans more than one sprint without dropping quality',
      'Mentor newer teammates through pairing and review',
      'Make technical choices and explain the trade-offs',
    ],
  },
  {
    id: 4,
    expected: 4.0,
    summary:
      'Leads complex GATE decisions, reduces ambiguity, and raises team effectiveness. Impact is amplified through others.',
    promotionGates: [
      'Lead complex initiatives and cut delivery risk for the team',
      'Improve GATE engineering practices with visible quality or speed gains',
      'Grow others into independent owners of their area',
      'Align the team on standards for APK Gate work',
      'Hold strong delivery across several review cycles',
    ],
  },
  {
    id: 5,
    expected: 5.0,
    summary:
      'Aligns architecture and execution across GATE areas. Handles high-impact ambiguity. Impact is cross-team.',
    promotionGates: [
      'Lead work that spans backend, frontend, DevOps, or service tracks',
      'Set technical direction for a shared GATE subsystem',
      'Shape roadmap choices with clear risk and trade-off framing',
      'Improve multi-area outcomes such as release reliability or lead time',
      'Coach senior engineers to take broader ownership',
    ],
  },
  {
    id: 6,
    expected: 6.0,
    summary:
      'Sets long-term technical direction, removes systemic risk, and ties GATE engineering to product outcomes. Impact is organizational.',
    promotionGates: [
      'Define and execute a multi-cycle technical strategy with measurable results',
      'Resolve systemic issues that span several GATE domains',
      'Grow other technical decision-makers on the team',
      'Keep technical direction aligned with PO and business constraints',
      'Influence senior stakeholders with credible technical judgment',
    ],
  },
  {
    id: 7,
    expected: 6.8,
    summary:
      'Shapes APK Gate technical trajectory and engineering culture. Impact is long-term and company-wide.',
    promotionGates: [
      'Sustain company-level impact on GATE quality and direction',
      'Raise engineering standards and culture across the product',
      'Develop the next generation of GATE technical leaders',
      'Influence product direction through technical vision',
      'Represent GATE engineering credibly outside the immediate team',
    ],
  },
];

const UNIVERSAL_GATES = [
  'Hold next-level scope for at least one full review cycle (scope, autonomy, influence)',
  'Keep delivery quality reliable with no open critical performance concerns',
  'Show collaboration, ownership, and knowledge sharing at the next level',
  'Prepare a short impact packet: outcomes, decisions, and evidence',
  'Receive lead recommendation and calibration based on evidence, not tenure',
];

// The scale runs 1-7 so that it lines up with the L1-L7 ladder: a score of N is
// the work expected of an LN engineer, which leaves an L3 room to grow instead of
// bumping against a ceiling.
const SCORING = {
  max: 7,
  scale: [
    { value: 7, label: 'Exceptional', hint: 'Sets the bar for the whole organisation' },
    { value: 6, label: 'Expert', hint: 'Sets technical direction beyond the team' },
    { value: 5, label: 'Advanced', hint: 'Drives outcomes across several areas' },
    { value: 4, label: 'Strong', hint: 'Owns a system and lifts the people around them' },
    { value: 3, label: 'Proficient', hint: 'Solid, independent delivery' },
    { value: 2, label: 'Developing', hint: 'Delivers defined work with support' },
    { value: 1, label: 'Foundational', hint: 'Learning the basics with close guidance' },
  ],
  verdicts: [
    {
      id: 'exceptional',
      label: 'Exceptional',
      band: 'Far above level',
      minDiff: 1.1,
      action: 'Nominate for promotion review and discuss next-level expectations',
    },
    {
      id: 'above',
      label: 'Above expectations',
      band: 'Above level',
      minDiff: 0.4,
      action: 'Acknowledge the work; give stretch assignments; accelerate the growth plan',
    },
    {
      id: 'meets',
      label: 'Meets expectations',
      band: 'At level',
      minDiff: -0.4,
      action: 'Standard merit and a normal development plan',
    },
    {
      id: 'below',
      label: 'Needs improvement',
      band: 'Below level',
      minDiff: -1.1,
      action: 'Written improvement plan, bi-weekly check-ins, targeted coaching',
    },
    {
      id: 'unsat',
      label: 'Unsatisfactory',
      band: 'Well below level',
      minDiff: -Infinity,
      action: 'Immediate performance plan with HR; weekly coaching',
    },
  ],
  antiPatterns: [
    {
      title: 'Recency bias',
      problem: 'Scoring only from the last sprint before review.',
      fix: 'Use notes collected through the period, not memory of the last week.',
    },
    {
      title: 'Velocity as a personal KPI',
      problem: 'Treating story points as an individual score.',
      fix: 'Velocity is a team planning tool. Score outcomes and quality, not raw points.',
    },
    {
      title: 'Halo or horn',
      problem: 'One strength or miss colors every domain.',
      fix: 'Score each domain on its own evidence.',
    },
    {
      title: 'Missing evidence',
      problem: 'Scores of 4+ or 2- with no named example.',
      fix: 'Tie outliers to a ticket, review, incident, or customer case.',
    },
    {
      title: 'Gaming the metric',
      problem: 'Optimizing the score instead of GATE outcomes.',
      fix: 'Prefer cycle time, release health, and customer impact.',
    },
    {
      title: 'Uncalibrated leads',
      problem: 'Different reviewers using the 1–7 scale differently.',
      fix: 'Calibrate once per cycle before scores are shared.',
    },
  ],
};

const AGILE = {
  id: 'agile',
  title: 'Agile & Scrum',
  icon: 'cycle',
  weight: 0.15,
  metrics: [
    metric(
      'sprint-reliability',
      'Sprint reliability',
      'Protects sprint goals with honest scope control and predictable finish quality on GATE work.',
      {
        1: 'Needs help to finish committed tickets inside the sprint.',
        2: 'Usually finishes assigned work; flags slip risk late in the sprint.',
        3: 'Holds commitments and splits or descope early when risk appears.',
        4: 'Stabilizes sprint outcomes for a whole slice of the board.',
        5: 'Raises the team’s planning honesty and finish rate across sprints.',
        6: 'Sets planning norms used by more than one GATE track.',
        7: 'Defines how GATE measures and protects delivery reliability.',
      },
    ),
    metric(
      'flow',
      'Flow',
      'Keeps work moving: limited WIP, fewer idle handoffs, faster feedback in Code Review and Release Test.',
      {
        1: 'Often waits on others without updating the ticket.',
        2: 'Moves own tickets; still piles up WIP under pressure.',
        3: 'Keeps personal WIP low and unblocks the next reviewer.',
        4: 'Removes recurring wait time (review, test, deploy) for the team.',
        5: 'Improves cross-role flow (dev → review → QA → PO).',
        6: 'Designs process changes that cut GATE cycle time.',
        7: 'Owns flow metrics and intervention for the product.',
      },
    ),
    metric(
      'blockers',
      'Blocker handling',
      'Surfaces blockers with enough context for Technical Review, QA, or PO to act the same day.',
      {
        1: 'Blockers appear only when someone asks.',
        2: 'Reports blockers in standup with partial context.',
        3: 'Writes a clear blocker (impact, tried steps, ask) and follows through.',
        4: 'Unblocks others and prevents the same stall from repeating.',
        5: 'Builds a habit of early risk flags across the sprint.',
        6: 'Changes how GATE tracks and clears systemic blockers.',
        7: 'Sets the standard for risk communication on the product.',
      },
    ),
    metric(
      'dod',
      'Definition of Done',
      'Marks work done only when review, tests, and GATE acceptance checks are actually complete.',
      {
        1: 'Needs reminders before a ticket is truly done.',
        2: 'Follows DoD on own tickets most of the time.',
        3: 'Does not close work with known gaps in test or review.',
        4: 'Holds peers to DoD in review and stand-up.',
        5: 'Tightens DoD where GATE releases have been bitten.',
        6: 'Aligns DoD across tracks (service, QA, product).',
        7: 'Owns GATE done-criteria at product level.',
      },
    ),
    metric(
      'process',
      'Team process',
      'Improves how GATE runs: retros, board hygiene, Original Story Point, and review queues.',
      {
        1: 'Attends ceremonies; rarely contributes changes.',
        2: 'Gives useful retro notes on own work.',
        3: 'Takes and finishes a process action item.',
        4: 'Drives a practice change the team actually keeps.',
        5: 'Improves a queue (Code Review, Technical Review, Release Test).',
        6: 'Designs process used by multiple GATE roles.',
        7: 'Sets GATE operating cadence with the lead and PO.',
      },
    ),
    metric(
      'breakdown',
      'Task breakdown',
      'Splits GATE work into testable tickets with scope, dependencies, and acceptance.',
      {
        1: 'Needs a lead to slice the work.',
        2: 'Breaks assigned stories into steps with help.',
        3: 'Writes tickets others can pick up without a meeting.',
        4: 'Slices risky GATE work so QA and PO can accept incrementally.',
        5: 'Teaches others to break down ambiguous UTM/firewall work.',
        6: 'Sets breakdown patterns for a subsystem.',
        7: 'Defines how GATE scopes large product bets.',
      },
    ),
    metric(
      'estimation',
      'Estimation',
      'Gives realistic estimates that include GATE complexity, dependencies, and release risk.',
      {
        1: 'Estimates are guesses; often far off.',
        2: 'Estimates assigned work; updates late when surprised.',
        3: 'Explains assumptions and revises when facts change.',
        4: 'Improves team forecast quality on similar work.',
        5: 'Accounts for cross-track dependencies in planning.',
        6: 'Calibrates estimation across GATE roles.',
        7: 'Owns how GATE forecasts major releases.',
      },
    ),
  ],
};

const SOFT = {
  id: 'soft',
  title: 'Soft skills',
  icon: 'people',
  weight: 0.15,
  metrics: [
    metric(
      'communication',
      'Communication',
      'Writes and speaks so GATE teammates, QA, and PO can act without extra decoding.',
      {
        1: 'Updates are sparse or hard to follow.',
        2: 'Communicates when asked; tickets sometimes lack context.',
        3: 'Proactive, concise updates in Jira and chat.',
        4: 'Frames issues so the next role can decide quickly.',
        5: 'Improves how the team writes tickets and reviews.',
        6: 'Aligns communication across GATE and adjacent teams.',
        7: 'Sets the voice of GATE engineering with stakeholders.',
      },
    ),
    metric(
      'collaboration',
      'Collaboration',
      'Works with backend, frontend, DevOps, DevNet, service, and QA as one GATE delivery line.',
      {
        1: 'Stays in own lane; handoffs are rough.',
        2: 'Cooperates when others reach out.',
        3: 'Seeks the right teammate before the work stalls.',
        4: 'Makes cross-role work smoother for everyone involved.',
        5: 'Builds working agreements between tracks.',
        6: 'Resolves recurring cross-team friction.',
        7: 'Designs how GATE collaborates with other APK groups.',
      },
    ),
    metric(
      'ownership',
      'Ownership',
      'Stays with a GATE issue until it is shipped, verified, or explicitly handed off.',
      {
        1: 'Drops work at the first handoff.',
        2: 'Owns assigned tickets through coding, not always through verify.',
        3: 'Follows work through review, test, and PO checking.',
        4: 'Picks up orphaned GATE issues that threaten the sprint.',
        5: 'Owns a subsystem’s health, not only tickets.',
        6: 'Owns outcomes across several roles or releases.',
        7: 'Owns GATE product health with the lead.',
      },
    ),
    metric(
      'feedback',
      'Feedback',
      'Gives and takes specific, respectful feedback in review and 1:1s.',
      {
        1: 'Avoids feedback or takes it personally.',
        2: 'Accepts feedback; rarely offers useful comments.',
        3: 'Gives concrete, kind review notes and acts on received feedback.',
        4: 'Raises the quality of team feedback loops.',
        5: 'Coaches others on how to review GATE work.',
        6: 'Builds a feedback culture across tracks.',
        7: 'Sets calibration norms for GATE performance talks.',
      },
    ),
    metric(
      'mentoring',
      'Mentoring',
      'Helps others get productive on APK Gate without creating a bottleneck.',
      {
        1: 'Not yet mentoring.',
        2: 'Answers questions when asked.',
        3: 'Pairs regularly and leaves notes others can reuse.',
        4: 'Has a clear mentee or onboarding impact.',
        5: 'Creates guides that shorten GATE ramp-up.',
        6: 'Builds mentoring capacity in other seniors.',
        7: 'Designs how GATE grows engineers.',
      },
    ),
    metric(
      'stakeholders',
      'Stakeholders',
      'Works with PO, support, and adjacent teams without surprising them.',
      {
        1: 'Needs a lead in every stakeholder conversation.',
        2: 'Joins PO/support discussions with preparation.',
        3: 'Handles routine stakeholder asks independently.',
        4: 'Sets expectations and says no with a clear alternative.',
        5: 'Represents GATE in cross-team forums.',
        6: 'Shapes stakeholder process (intake, severity, SLA).',
        7: 'Is a trusted face of GATE engineering externally.',
      },
    ),
    metric(
      'pressure',
      'Calm under pressure',
      'Stays useful during incidents, release crunches, and customer escalations.',
      {
        1: 'Freezes or goes quiet when things break.',
        2: 'Helps with guidance; stress shows in communication.',
        3: 'Stays factual and useful in a GATE incident.',
        4: 'Steadies others during a bad release or outage.',
        5: 'Runs incident comms and follow-up for the team.',
        6: 'Improves how GATE handles high-severity events.',
        7: 'Sets incident culture for the product.',
      },
    ),
  ],
};

const DELIVERY = {
  id: 'delivery',
  title: 'Delivery & quality',
  icon: 'ship',
  weight: 0.1,
  metrics: [
    metric(
      'predictable',
      'Predictable delivery',
      'Finishes GATE work when promised, or renegotiates before the date slips silently.',
      {
        1: 'Dates slip without warning.',
        2: 'Usually on time for small work; larger items drift.',
        3: 'Forecasts own work and flags slip early.',
        4: 'Makes a stream of GATE work predictable for the board.',
        5: 'Improves team-level date honesty.',
        6: 'Sets delivery contracts across tracks.',
        7: 'Owns GATE release predictability with PO.',
      },
    ),
    metric(
      'release-quality',
      'Release quality',
      'Changes land in GATE releases without avoidable rollback, hotfix, or support storm.',
      {
        1: 'Changes often bounce in Release Test or production.',
        2: 'Most changes land; regressions still surprise QA.',
        3: 'Releases of owned work are boring in a good way.',
        4: 'Reduces regression class for a GATE area.',
        5: 'Raises release bar for the whole team.',
        6: 'Designs quality gates used across GATE versions.',
        7: 'Owns GATE release quality strategy.',
      },
    ),
    metric(
      'incidents',
      'Incident follow-through',
      'When GATE breaks, drives detection, mitigation, and a fix that stays fixed.',
      {
        1: 'Needs someone else to drive every incident.',
        2: 'Helps mitigate; follow-up tickets linger.',
        3: 'Owns mitigation and a durable fix for assigned incidents.',
        4: 'Leads post-incident actions the team actually completes.',
        5: 'Cuts repeat incidents in a GATE subsystem.',
        6: 'Improves incident practice across the product.',
        7: 'Sets GATE reliability response at org level.',
      },
    ),
  ],
};

const GROWTH = {
  id: 'growth',
  title: 'Growth',
  icon: 'grow',
  weight: 0.1,
  metrics: [
    metric(
      'learning',
      'Learning the product',
      'Deepens APK Gate knowledge: UTM behavior, policy, logging, HA, and customer usage.',
      {
        1: 'Learns only what the current ticket requires.',
        2: 'Builds a basic map of GATE modules.',
        3: 'Connects own work to real customer and ops behavior.',
        4: 'Becomes the go-to person for a GATE area.',
        5: 'Spreads product knowledge across roles.',
        6: 'Shapes how GATE learns as a team.',
        7: 'Defines GATE technical mastery for the company.',
      },
    ),
    metric(
      'sharing',
      'Knowledge sharing',
      'Leaves the next person faster: notes, runbooks, reviews, and short write-ups.',
      {
        1: 'Knowledge stays in chat or in one head.',
        2: 'Shares when asked.',
        3: 'Writes useful notes on non-obvious GATE work.',
        4: 'Produces guides others actually use.',
        5: 'Runs sessions that change how the team works.',
        6: 'Builds a knowledge system across tracks.',
        7: 'Owns GATE knowledge strategy.',
      },
    ),
    metric(
      'self-direction',
      'Self-direction',
      'Finds the next useful GATE problem without waiting for a perfectly specified ticket.',
      {
        1: 'Waits to be assigned.',
        2: 'Asks for the next task when idle.',
        3: 'Pulls the highest-value ready work and clarifies it.',
        4: 'Creates well-shaped work the board needs.',
        5: 'Points the team at the right problems.',
        6: 'Sets a backlog strategy with the lead and PO.',
        7: 'Sets GATE investment themes.',
      },
    ),
    metric(
      'career',
      'Career development',
      'Works a visible growth plan: skills, scope, and evidence toward the next GATE level.',
      {
        1: 'No plan; growth is accidental.',
        2: 'Has goals; follow-through is uneven.',
        3: 'Runs a simple plan and shows evidence at review.',
        4: 'Helps others build a credible growth plan.',
        5: 'Raises the bar for how GATE talks about levels.',
        6: 'Designs development paths for a track.',
        7: 'Owns GATE talent development with leadership.',
      },
    ),
  ],
};

export function defaultSharedDomains() {
  return [AGILE, SOFT, DELIVERY, GROWTH];
}

export function defaultLevels() {
  return LEVELS;
}

export function defaultScoring() {
  return SCORING;
}

export function defaultUniversalGates() {
  return UNIVERSAL_GATES;
}

export function defaultRoles() {
  return [
    {
      id: 'backend',
      name: 'Backend',
      icon: 'hex',
      technicalWeight: 0.5,
      metrics: [
        metric(
          'be-testing',
          'Service testing',
          'Builds tests that protect GATE services: policy, sessions, APIs, and regressions that would escape to Release Test.',
          {
            1: 'Adds tests only when asked; happy path only.',
            2: 'Covers assigned changes including a few failure cases.',
            3: 'Consistently tests business logic and error paths for owned services.',
            4: 'Designs a test strategy for a complex GATE service or integration.',
            5: 'Raises backend test confidence for the team (fewer escaped defects).',
            6: 'Standardizes backend testing across GATE services.',
            7: 'Sets organization-wide backend quality baseline for GATE.',
          },
        ),
        metric(
          'be-code',
          'Maintainable services',
          'Writes backend code the next GATE engineer can change safely: clear structure, naming, and reviewable diffs.',
          {
            1: 'Code works with heavy guidance; hard to follow.',
            2: 'Readable on small changes; larger diffs need cleanup in review.',
            3: 'Produces review-friendly changes with coherent structure.',
            4: 'Simplifies a messy GATE module without breaking behavior.',
            5: 'Sets coding patterns others copy in backend reviews.',
            6: 'Drives maintainability standards across services.',
            7: 'Defines GATE backend engineering standards.',
          },
        ),
        metric(
          'be-data',
          'Data, logs, and state',
          'Models GATE state so logs, sessions, config, and persistence stay consistent and queryable.',
          {
            1: 'Touches storage/logging with close review.',
            2: 'Makes correct local changes; misses some integrity cases.',
            3: 'Designs data/log changes that match how ops will query them.',
            4: 'Evolves schemas or log contracts without silent breakage.',
            5: 'Improves GATE observability data for several services.',
            6: 'Sets data/log standards used across the product.',
            7: 'Owns GATE data and telemetry strategy.',
          },
        ),
        metric(
          'be-design',
          'Service design',
          'Designs GATE backend boundaries: APIs, policy evaluation, HA, and failure behavior.',
          {
            1: 'Implements a spec; does not yet propose design.',
            2: 'Suggests small design tweaks on assigned work.',
            3: 'Designs a feature-sized service change with trade-offs.',
            4: 'Leads design for a complex GATE subsystem.',
            5: 'Aligns backend design across multiple services.',
            6: 'Sets architecture direction for GATE backend.',
            7: 'Owns long-term GATE backend architecture.',
          },
        ),
        metric(
          'be-prod',
          'Production behavior',
          'Ships backend changes that hold up under real GATE load, failover, and customer config.',
          {
            1: 'Production issues on owned changes are common.',
            2: 'Most changes hold; misses some operational cases.',
            3: 'Owned features behave in production as intended.',
            4: 'Anticipates operational failure modes before release.',
            5: 'Improves production resilience for a GATE area.',
            6: 'Raises backend reliability across the product.',
            7: 'Owns GATE backend reliability strategy.',
          },
        ),
        metric(
          'be-debug',
          'Backend diagnosis',
          'Debugs GATE services with evidence: logs, traces, configs, and reproduction — not guess-and-patch.',
          {
            1: 'Needs a senior to find the root cause.',
            2: 'Debugs with help; sometimes patches symptoms.',
            3: 'Finds root cause on owned services and proves it.',
            4: 'Diagnoses cross-service GATE failures.',
            5: 'Teaches debugging patterns; shortens incident time.',
            6: 'Improves how GATE diagnoses backend failures.',
            7: 'Sets diagnosis practice for the product.',
          },
        ),
      ],
    },
    {
      id: 'frontend',
      name: 'Frontend',
      icon: 'diamond',
      technicalWeight: 0.5,
      metrics: [
        metric(
          'fe-ui',
          'GATE UI quality',
          'Builds admin and operator UI that is clear under real GATE workflows (policy, logs, status).',
          {
            1: 'Implements screens with heavy design/lead help.',
            2: 'Delivers assigned screens; edge states are incomplete.',
            3: 'Handles empty, error, loading, and permission states.',
            4: 'Improves a complex GATE flow so operators make fewer mistakes.',
            5: 'Raises UI consistency across GATE pages.',
            6: 'Sets frontend UX patterns for the product.',
            7: 'Owns GATE operator experience strategy.',
          },
        ),
        metric(
          'fe-state',
          'State and data flow',
          'Manages client state, API errors, and refresh so GATE UI stays truthful about device/system state.',
          {
            1: 'State bugs are frequent; needs pairing.',
            2: 'Handles simple fetch/update; races still appear.',
            3: 'Keeps UI state consistent with GATE APIs.',
            4: 'Designs data flow for a complex console area.',
            5: 'Simplifies shared frontend state for the team.',
            6: 'Sets data-layer standards for GATE UI.',
            7: 'Owns GATE frontend architecture.',
          },
        ),
        metric(
          'fe-a11y',
          'Usability',
          'Makes GATE UI usable for operators: density, keyboard, contrast, and Persian/English where required.',
          {
            1: 'Visual only; usability issues ship unnoticed.',
            2: 'Fixes obvious usability bugs when reported.',
            3: 'Checks flows as an operator would, including errors.',
            4: 'Removes a class of operator confusion in a module.',
            5: 'Defines usability checks the team runs before PO Checking.',
            6: 'Sets accessibility/usability bar for GATE UI.',
            7: 'Owns GATE console usability at product level.',
          },
        ),
        metric(
          'fe-test',
          'Frontend verification',
          'Protects GATE UI with tests or disciplined manual scripts that catch regressions before Release Test.',
          {
            1: 'Relies entirely on others to find UI regressions.',
            2: 'Checks happy path before handoff.',
            3: 'Covers critical flows and obvious failure UI.',
            4: 'Adds durable tests or checklists for a GATE module.',
            5: 'Raises frontend catch-rate for the team.',
            6: 'Standardizes frontend verification across the console.',
            7: 'Sets GATE UI quality strategy.',
          },
        ),
        metric(
          'fe-perf',
          'UI performance',
          'Keeps GATE consoles responsive on real data volumes (sessions, logs, policy lists).',
          {
            1: 'Performance issues ship unnoticed.',
            2: 'Fixes slowness when someone reports it.',
            3: 'Avoids obvious jank on owned pages.',
            4: 'Profiles and fixes a heavy GATE view.',
            5: 'Sets performance budgets for key screens.',
            6: 'Improves performance patterns across the UI.',
            7: 'Owns GATE UI performance strategy.',
          },
        ),
        metric(
          'fe-debug',
          'Frontend diagnosis',
          'Finds whether a GATE console bug is UI, API, or product behavior — then proves it.',
          {
            1: 'Needs help to locate the layer at fault.',
            2: 'Debugs with browser tools on assigned bugs.',
            3: 'Isolates UI vs backend with evidence.',
            4: 'Diagnoses tricky operator-only failures.',
            5: 'Shortens UI incident time for the team.',
            6: 'Improves frontend diagnosis practice.',
            7: 'Sets GATE console reliability practice.',
          },
        ),
      ],
    },
    {
      id: 'devops',
      name: 'DevOps',
      icon: 'loop',
      technicalWeight: 0.5,
      metrics: [
        metric(
          'do-cicd',
          'CI/CD',
          'Keeps GATE build, test, and package pipelines trustworthy and fast enough for the sprint cadence.',
          {
            1: 'Follows existing jobs; cannot yet change them safely.',
            2: 'Fixes simple pipeline breaks with help.',
            3: 'Owns pipeline changes for assigned GATE components.',
            4: 'Improves pipeline reliability or feedback time.',
            5: 'Raises CI quality used by several GATE tracks.',
            6: 'Sets CI/CD standards for the product.',
            7: 'Owns GATE delivery pipeline strategy.',
          },
        ),
        metric(
          'do-release',
          'Release engineering',
          'Produces GATE builds, artifacts, and version notes that QA and service can actually ship.',
          {
            1: 'Needs a checklist from someone else for every release.',
            2: 'Runs a known release path with occasional misses.',
            3: 'Executes GATE releases without drama for owned streams.',
            4: 'Hardens release steps that previously failed.',
            5: 'Makes multi-component GATE releases repeatable.',
            6: 'Designs release process across versions.',
            7: 'Owns GATE release engineering.',
          },
        ),
        metric(
          'do-obs',
          'Observability',
          'Makes GATE health visible: metrics, logs, alerts that operators and developers can use.',
          {
            1: 'Uses existing dashboards only.',
            2: 'Adds a metric or log when asked.',
            3: 'Instruments owned systems so failures are obvious.',
            4: 'Improves alert quality (less noise, faster signal).',
            5: 'Builds observability that several roles rely on.',
            6: 'Sets telemetry standards for GATE.',
            7: 'Owns GATE observability strategy.',
          },
        ),
        metric(
          'do-env',
          'Environments',
          'Keeps GATE lab, staging, and related environments close enough to reality to catch release risk.',
          {
            1: 'Uses environments; cannot repair them.',
            2: 'Fixes simple env issues with help.',
            3: 'Maintains environments needed for GATE sprint work.',
            4: 'Removes a class of “works in lab only” failures.',
            5: 'Designs env strategy for QA and service.',
            6: 'Standardizes GATE environments across sites.',
            7: 'Owns GATE environment strategy.',
          },
        ),
        metric(
          'do-sec',
          'Pipeline and infra security',
          'Protects GATE delivery: secrets, access, image/supply chain, and least privilege.',
          {
            1: 'Follows security rules when reminded.',
            2: 'Handles secrets correctly on assigned work.',
            3: 'Does not introduce obvious security gaps in pipelines.',
            4: 'Closes a real pipeline or infra security gap.',
            5: 'Raises security baseline for GATE delivery.',
            6: 'Sets secure-delivery standards.',
            7: 'Owns GATE delivery security posture.',
          },
        ),
        metric(
          'do-ops',
          'Operational response',
          'When build, deploy, or infra breaks, restores GATE delivery and leaves a durable fix.',
          {
            1: 'Escalates immediately without a first diagnosis.',
            2: 'Restores service with help; weak write-up.',
            3: 'Restores and documents a durable fix.',
            4: 'Leads ops incidents that block the GATE board.',
            5: 'Cuts repeat delivery-infra incidents.',
            6: 'Improves GATE ops practice.',
            7: 'Sets GATE operational excellence.',
          },
        ),
      ],
    },
    {
      id: 'devnet',
      name: 'DevNet',
      icon: 'net',
      technicalWeight: 0.5,
      metrics: [
        metric(
          'dn-auto',
          'Network automation',
          'Automates repeatable GATE/network work with scripts or APIs instead of one-off console clicks.',
          {
            1: 'Runs steps manually from a runbook.',
            2: 'Writes small scripts for assigned tasks.',
            3: 'Automates a real GATE/network workflow others reuse.',
            4: 'Designs automation that survives device or API changes.',
            5: 'Raises automation adoption on the team.',
            6: 'Sets automation standards for GATE/network work.',
            7: 'Owns GATE network-automation strategy.',
          },
        ),
        metric(
          'dn-api',
          'Device and API integration',
          'Integrates GATE with network platforms (REST, SSH, vendors) with clear contracts and failure handling.',
          {
            1: 'Calls APIs with heavy guidance.',
            2: 'Implements a specified integration; error handling is thin.',
            3: 'Builds a reliable integration with retries and clear errors.',
            4: 'Designs a multi-device integration for GATE.',
            5: 'Improves integration quality others depend on.',
            6: 'Sets API integration patterns for the product.',
            7: 'Owns GATE north/south integration architecture.',
          },
        ),
        metric(
          'dn-policy',
          'Policy as code',
          'Treats firewall/UTM policy and network intent as reviewable, testable change — not tribal knowledge.',
          {
            1: 'Applies policy changes by instruction only.',
            2: 'Documents changes; little validation.',
            3: 'Makes policy changes reviewable and reversible.',
            4: 'Adds checks that catch dangerous policy diffs.',
            5: 'Spreads policy-as-code practice on GATE.',
            6: 'Sets policy-change standards across environments.',
            7: 'Owns GATE policy lifecycle.',
          },
        ),
        metric(
          'dn-net',
          'Network literacy',
          'Reasons about L3–L7 behavior that APK Gate must inspect, NAT, route, or log.',
          {
            1: 'Needs a senior to interpret packet/path issues.',
            2: 'Reads basic routing/firewall symptoms with help.',
            3: 'Explains path, NAT, and policy hits for owned cases.',
            4: 'Diagnoses non-obvious GATE/network interactions.',
            5: 'Teaches network reasoning to software teammates.',
            6: 'Sets the network bar for GATE engineers.',
            7: 'Owns GATE network-domain expertise.',
          },
        ),
        metric(
          'dn-tooling',
          'Tooling',
          'Builds small internal tools that make GATE network work faster and safer.',
          {
            1: 'Uses tools others built.',
            2: 'Patches a tool when asked.',
            3: 'Ships a tool or script the team actually runs.',
            4: 'Turns a painful workflow into a maintained tool.',
            5: 'Portfolio of tools used across roles.',
            6: 'Sets tooling standards and ownership.',
            7: 'Owns GATE DevNet platform tooling.',
          },
        ),
        metric(
          'dn-debug',
          'Net + software diagnosis',
          'Splits “device, path, GATE software, or config” and proves it with captures, logs, and diffs.',
          {
            1: 'Cannot yet isolate the layer.',
            2: 'Debugs with help from service or backend.',
            3: 'Produces a clear root-cause story on owned cases.',
            4: 'Leads mixed net/software incidents.',
            5: 'Shortens mean-time-to-diagnosis for the team.',
            6: 'Improves GATE diagnosis playbooks.',
            7: 'Sets GATE net/software incident practice.',
          },
        ),
      ],
    },
    {
      id: 'service',
      name: 'Service',
      icon: 'wrench',
      technicalWeight: 0.5,
      metrics: [
        metric(
          'sv-deploy',
          'Deployment',
          'Installs and upgrades GATE in customer or lab topologies without avoidable downtime or leftover config debt.',
          {
            1: 'Follows a script; stalls on any deviation.',
            2: 'Completes standard deploys; unusual topologies need help.',
            3: 'Owns a deploy/upgrade including rollback plan.',
            4: 'Handles messy real-world topologies cleanly.',
            5: 'Improves deploy playbooks the team uses.',
            6: 'Sets GATE deploy standards across sites.',
            7: 'Owns GATE field-deploy strategy.',
          },
        ),
        metric(
          'sv-trouble',
          'Troubleshooting',
          'Turns a customer or lab symptom into a GATE root cause using logs, policy, sessions, and topology.',
          {
            1: 'Collects info; diagnosis comes from someone else.',
            2: 'Solves common cases; escalates the rest early.',
            3: 'Closes typical GATE cases with a clear write-up.',
            4: 'Solves unusual multi-factor failures.',
            5: 'Raises first-time-fix quality for the service track.',
            6: 'Designs troubleshooting paths used by others.',
            7: 'Owns GATE field-diagnosis excellence.',
          },
        ),
        metric(
          'sv-config',
          'Configuration quality',
          'Leaves GATE configs that are correct, documented, and supportable after you leave the session.',
          {
            1: 'Configs work in the moment; later people cannot follow them.',
            2: 'Documents the change; structure is inconsistent.',
            3: 'Produces clean, named, supportable GATE configs.',
            4: 'Repairs config debt that caused repeat tickets.',
            5: 'Sets config patterns for common GATE designs.',
            6: 'Standardizes configuration across customers/labs.',
            7: 'Owns GATE configuration practice.',
          },
        ),
        metric(
          'sv-customer',
          'Customer communication',
          'Explains GATE status, risk, and next steps in language PO and customers can use.',
          {
            1: 'Needs a lead on every customer thread.',
            2: 'Updates when asked; tone is sometimes too internal.',
            3: 'Gives timely, plain-language status and asks.',
            4: 'Manages tense escalations without hiding risk.',
            5: 'Improves how GATE service communicates as a group.',
            6: 'Sets customer-comm standards with PO/support.',
            7: 'Owns GATE customer engineering voice.',
          },
        ),
        metric(
          'sv-escalation',
          'Escalation and knowledge',
          'Escalates to backend/QA/DevNet with a complete packet — and feeds the fix back into runbooks.',
          {
            1: 'Escalates with “it doesn’t work”.',
            2: 'Includes logs; missing topology or repro.',
            3: 'Sends a complete packet and tracks the answer.',
            4: 'Turns escalations into team knowledge.',
            5: 'Reduces repeat escalations in a GATE area.',
            6: 'Designs the escalation path across roles.',
            7: 'Owns GATE service knowledge system.',
          },
        ),
        metric(
          'sv-ops',
          'Operational ownership',
          'Stays with a GATE field issue through workaround, fix, and confirmation — not just the first reply.',
          {
            1: 'Hands off at the first hard step.',
            2: 'Owns simple cases to close.',
            3: 'Owns assigned cases through verification.',
            4: 'Picks up aging GATE issues that threaten customers.',
            5: 'Improves service SLA outcomes for the team.',
            6: 'Sets operational ownership norms.',
            7: 'Owns GATE service operations with leadership.',
          },
        ),
      ],
    },
    {
      id: 'qa',
      name: 'QA',
      icon: 'check',
      technicalWeight: 0.5,
      metrics: [
        metric(
          'qa-design',
          'Test design',
          'Designs GATE test coverage around risk: policy, HA, upgrade, logging, and operator paths — not only happy clicks.',
          {
            1: 'Executes cases others wrote.',
            2: 'Adds cases for assigned features with help.',
            3: 'Designs a feature test set that finds real defects.',
            4: 'Designs risk-based coverage for a GATE area.',
            5: 'Raises test design quality for the team.',
            6: 'Sets GATE test-design standards.',
            7: 'Owns GATE quality strategy.',
          },
        ),
        metric(
          'qa-release',
          'Release Test',
          'Runs GATE Release Test so the board gets a clear go/no-go, not a vague “still checking”.',
          {
            1: 'Needs a list for every pass; status is late.',
            2: 'Completes a known suite; reporting is delayed.',
            3: 'Finishes planned Release Test with a clear result.',
            4: 'Shortens Release Test without losing signal.',
            5: 'Makes Release Test a reliable GATE gate.',
            6: 'Designs release-test strategy across versions.',
            7: 'Owns GATE release-test practice.',
          },
        ),
        metric(
          'qa-defects',
          'Defect quality',
          'Writes GATE bugs that developers can reproduce: build, topology, expected vs actual, evidence.',
          {
            1: 'Reports are incomplete; bounce in review.',
            2: 'Most bugs are usable; some missing evidence.',
            3: 'Defects are complete and correctly severity-tagged.',
            4: 'Clusters defects so backend/frontend can see the pattern.',
            5: 'Improves defect quality across the team.',
            6: 'Sets defect standards used by service and QA.',
            7: 'Owns GATE defect practice.',
          },
        ),
        metric(
          'qa-negative',
          'Negative and security testing',
          'Probes GATE the way a hostile or clumsy operator would: bad config, privilege, malformed traffic.',
          {
            1: 'Tests only the demonstrated happy path.',
            2: 'Adds a few negative cases when reminded.',
            3: 'Includes meaningful negative cases on owned features.',
            4: 'Finds a class of abuse/misconfig bugs.',
            5: 'Builds negative/security checks into the suite.',
            6: 'Sets GATE negative-test standards.',
            7: 'Owns GATE product-security test strategy.',
          },
        ),
        metric(
          'qa-auto',
          'Test automation',
          'Automates stable GATE checks so humans spend time on exploratory and release risk.',
          {
            1: 'No automation yet.',
            2: 'Extends existing automation with help.',
            3: 'Adds reliable automated checks for owned areas.',
            4: 'Turns a painful manual GATE suite into automation.',
            5: 'Raises automation value for the whole team.',
            6: 'Sets automation standards and ownership.',
            7: 'Owns GATE test-automation strategy.',
          },
        ),
        metric(
          'qa-risk',
          'Risk communication',
          'Tells PO and the lead what GATE can ship, what is unknown, and what would bite customers.',
          {
            1: 'Status is a list of cases, not a risk call.',
            2: 'Flags obvious blockers late.',
            3: 'Gives a clear risk summary with evidence.',
            4: 'Changes the release call with a well-argued risk.',
            5: 'Improves how GATE talks about quality risk.',
            6: 'Sets go/no-go language with PO and lead.',
            7: 'Owns GATE quality-risk communication.',
          },
        ),
      ],
    },
  ];
}
